# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        # le nom du "filter set"
        square:
            # ajustez la qualité de l'image à 75% de
            quality: 75
            filters:
                thumbnail:
                    size: [400,400]
                    mode: outbound




